In [1]:
import numpy as np

class Neuron:


  def __init__(self, input, weights=None):
    if weights:
      self.weights = weights
    else:
      self.weights = np.random.randint(10, size=(len(input), len(input[0])))
    self.input = input
    self.output = self.relu()

  def __str__(self):
    strWeights = [x for x in self.weights]
    text = f"The weights used are:{strWeights}\n\nOutput: {str(self.output)}"
    return text

  def adder(self):
    result = 0
    for i in range(len(self.input)):
      result += self.input[i] * self.weights[i]
    return result


  def relu(self):
    if self.adder() > 0:  # max (0, input)
      return self.adder()
    return 0


# test
input = [[5],
         [6],
         [7]]

test = Neuron(input)
print(test)

The weights used are:[array([4]), array([9]), array([2])]

Output: [88]


In [2]:
class NNetwork:  # Feed-forward Neuron Network class

  def __init__(self, activation_func="sig"): # default activation function will be 'relu'
    self.input = []
    self.weights = None
    self.output = None
    self.bias = np.random.rand(1, 1) - 0.5  # since there will be only 1 output neuron
    self.neuron_list = []
    self.activation = activation_func

  def __str__(self):
    return f"There are {len(self.neuron_list)} neurons present in Neural Network.\nOutput using {self.activation} activation: {self.output}"

  def feed_forward(self, input): 
   ## - Feed-forward formula:
   # output = np.dot(input, weights) + bias
   #  This summed function is applied over an Activation function
   self.output = np.dot(self.input, self.weights) + self.bias

  def add(self, Neuron):
    self.input.append(Neuron.output)  # the output of neurons will be the current input for this network output
    self.neuron_list.append(Neuron)
    # update number of weights for every addition of Neuron
    # code here

  def adder(self):  # adder for all neurons within neuron_list
    result = 0
    for i in range(len(self.neuron_list)):
      result += self.input[i] * self.weights[i]
    return result

  def activate(self): # default: sigmoid activation function
    if self.activation != "sig":
      # do other activation function
      raise NotImplementedError
    # Sigmoid formula : 1/(1+e^(-x))
    else: self.output = 1 / (1 + np.e ** (-self.adder()))

  def setWeight(self, weights): # this function will be used for statically created weights
    self.weights = weights

In [3]:
# Create 5 neurons with 3 inputs and 1 output
n_1 = Neuron([[5],
              [6],
              [7]])

n_2 = Neuron([[5],
              [6],
              [7]])

n_3 = Neuron([[5],
              [6],
              [7]])

n_4 = Neuron([[5],
              [6],
              [7]])

n_5 = Neuron([[5],
              [6],
              [7]])

# Create a network of neurons with 1 output neuron
network = NNetwork()
network.add(n_1)
network.add(n_2)
network.add(n_3)
network.add(n_4)
network.add(n_5)

# statically create weights for validation of NNetwork class
network.setWeight([[6],
                   [5],
                   [4],
                   [3],
                   [2]])

network.activate() # compute using sigmoid activation

for i in range(len(network.neuron_list)):
  print(f"Neuron {i+1} : Output -> {network.neuron_list[i].output}\nWeight {i+1}\n{network.neuron_list[i].weights}\n")

Neuron 1 : Output -> [53]
Weight 1
[[4]
 [2]
 [3]]

Neuron 2 : Output -> [75]
Weight 2
[[7]
 [2]
 [4]]

Neuron 3 : Output -> [67]
Weight 3
[[6]
 [5]
 [1]]

Neuron 4 : Output -> [62]
Weight 4
[[6]
 [3]
 [2]]

Neuron 5 : Output -> [79]
Weight 5
[[6]
 [0]
 [7]]



In [4]:
# print output of Neural Network
print(network)

There are 5 neurons present in Neural Network.
Output using sig activation: [1.]


- The output is correct since the output in sigmoid activation function is either 1 or 0.

## - Feed-forward formula:
 self.output = np.dot(self.input, self.weights) + self.bias
